# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Camilo/Desktop/bloques_separados5/atg_ram/atg_ram/atg_ram.srcs/sources_1/bd/Atg_ram/ip/Atg_ram_axi_traffic_gen_0_0/Atg_ram_axi_traffic_gen_0_0.xci
# IP: The module: 'Atg_ram_axi_traffic_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Camilo/Desktop/bloques_separados5/atg_ram/atg_ram/atg_ram.srcs/sources_1/bd/Atg_ram/ip/Atg_ram_axi_traffic_gen_0_0/Atg_ram_axi_traffic_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Atg_ram_axi_traffic_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Camilo/Desktop/bloques_separados5/atg_ram/atg_ram/atg_ram.srcs/sources_1/bd/Atg_ram/ip/Atg_ram_axi_traffic_gen_0_0/Atg_ram_axi_traffic_gen_0_0.xci
# IP: The module: 'Atg_ram_axi_traffic_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Camilo/Desktop/bloques_separados5/atg_ram/atg_ram/atg_ram.srcs/sources_1/bd/Atg_ram/ip/Atg_ram_axi_traffic_gen_0_0/Atg_ram_axi_traffic_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Atg_ram_axi_traffic_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
