# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/proyectos/Zybo-Z7-Master.xdc

# Block Designs: bd/Atg_ram/Atg_ram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Atg_ram || ORIG_REF_NAME==Atg_ram} -quiet] -quiet

# IP: bd/Atg_ram/ip/Atg_ram_Ram_IP_0_0/Atg_ram_Ram_IP_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Atg_ram_Ram_IP_0_0 || ORIG_REF_NAME==Atg_ram_Ram_IP_0_0} -quiet] -quiet

# IP: bd/Atg_ram/ip/Atg_ram_selector_led2_0_0/Atg_ram_selector_led2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Atg_ram_selector_led2_0_0 || ORIG_REF_NAME==Atg_ram_selector_led2_0_0} -quiet] -quiet

# IP: bd/Atg_ram/ip/Atg_ram_verif_led_or_0_0/Atg_ram_verif_led_or_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Atg_ram_verif_led_or_0_0 || ORIG_REF_NAME==Atg_ram_verif_led_or_0_0} -quiet] -quiet

# IP: bd/Atg_ram/ip/Atg_ram_operator_full_0_0/Atg_ram_operator_full_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Atg_ram_operator_full_0_0 || ORIG_REF_NAME==Atg_ram_operator_full_0_0} -quiet] -quiet

# IP: bd/Atg_ram/ip/Atg_ram_operator_full_1_0/Atg_ram_operator_full_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Atg_ram_operator_full_1_0 || ORIG_REF_NAME==Atg_ram_operator_full_1_0} -quiet] -quiet

# IP: bd/Atg_ram/ip/Atg_ram_operator_full_2_0/Atg_ram_operator_full_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Atg_ram_operator_full_2_0 || ORIG_REF_NAME==Atg_ram_operator_full_2_0} -quiet] -quiet

# IP: bd/Atg_ram/ip/Atg_ram_op_choser_0_0/Atg_ram_op_choser_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Atg_ram_op_choser_0_0 || ORIG_REF_NAME==Atg_ram_op_choser_0_0} -quiet] -quiet

# IP: bd/Atg_ram/ip/Atg_ram_axi_traffic_gen_0_0/Atg_ram_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Atg_ram_axi_traffic_gen_0_0 || ORIG_REF_NAME==Atg_ram_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/Atg_ram/ip/Atg_ram_ngate_0_0/Atg_ram_ngate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Atg_ram_ngate_0_0 || ORIG_REF_NAME==Atg_ram_ngate_0_0} -quiet] -quiet

# XDC: bd/Atg_ram/Atg_ram_ooc.xdc
